name: Continous-Integration-Practice

on:
  push:
    branches:
      - 'master'
      - 'CI-probes'
  pull_request:
    branches:
      - 'master'
  workflow_dispatch:
    inputs:
      browserName:
        description: 'Browser Type'
        required: false
        type: string
        default: 'CHROME'

jobs:
  start-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - name: Set up JDK 17
        uses: actions/setup-java@v4.3.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          mvn clean

      - name: Run TestNG tests
        run: |
          mvn test -DsuiteXmlFile=src/test/resources/suiteProductPurchaseTest.xml

      - name: Get Allure history
        uses: actions/checkout@v4.1.7
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure report action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
            allure_results: ${{ vars.ALLURE_RESULTS_PATH }}
            gh_pages: gh-pages
            allure_report: allure-report
            allure_history: allure-history

      - name: Deploy report to Github Pages
        uses: crazy-max/ghaction-github-pages@v4
        if: always()
        with:
          target_branch: gh-pages
          build_dir: allure-history
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
