name: Continuous-Integration-Practice

on:
  push:
    branches:
      - 'master'
      - 'CI-probes'
  pull_request:
    branches:
      - 'master'
  workflow_dispatch:
    inputs:
      suite:
        description: 'Select the test suite to run'
        default: 'E2E'
        required: false
        type: string
        options:
          - 'E2E'
          - 'Purchase one product'
          - 'Log Out'
          - 'Cart Test'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7

      - name: Set up JDK 17
        uses: actions/setup-java@v4.3.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          mvn clean

      - name: Debug Selected Suite Value
        run: |
          echo "Selected suite: ${{ github.event.inputs.suite }}"
     
     

      - name: 'Execute the selected TestNG suite'
        run: |
          SUITE_PATH="src/test/resources"
          case "${{ github.event.inputs.suite }}" in
            "E2E")
              mvn test -Dsurefire.suiteXmlFiles=${SUITE_PATH}/Suite.xml
              ;;
            "Purchase one product")
              mvn test -Dsurefire.suiteXmlFiles=${SUITE_PATH}/suiteProductPurchaseTest.xml
              ;;
            "Log Out")
              mvn test -Dsurefire.suiteXmlFiles=${SUITE_PATH}/suiteLogOutTest.xml
              ;;
            "Cart Test")
              mvn test -Dsurefire.suiteXmlFiles=${SUITE_PATH}/suiteRemoveProductsFromTheCartTest.xml
              ;;
            *)
              echo "Invalid suite selected"
              exit 1
              ;;
          esac

      - name: Get Allure history
        uses: actions/checkout@v4.1.7
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure report action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: ${{ vars.ALLURE_RESULTS_PATH }}
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        uses: crazy-max/ghaction-github-pages@v4
        if: always()
        with:
          target_branch: gh-pages
          build_dir: allure-history
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}